### ISSUE TITLE
# Task 3: Creating a Lambda Function

### ISSUE THREAD

**Issue by Suzannestacks** [Suzannestacks/Cloudresume#3]

**Comment by Suzannestacks** [comment]
# Task 3: Create a serverless function
- [ ] Setting up a new Lambda function in the AWS Console.
- [ ] Specify code to fetch data from the database and run(display) it upon the trigger.
- [ ] Contents displayed should be in JSON
- [ ] Test Lambda functions locally
- [ ] Deploy Lambda Functions
