### ISSUE TITLE
Task 4: API Gateway Configuration

### ISSUE THREAD

**Issue by Suzannestacks** [Suzannestacks/Cloudresume#4]

**Comment by Suzannestacks** [comment]
# Task 4: API setup
- [ ] Create a new REST API in API Gateway
- [ ]  Include accessibility via URL.
- [ ] Define the resources (e.g., '/resume')
- [ ] Use the URL to get sample data in JSON.
