### ISSUE TITLE
# Task 5: CI/CD pipeline using Github Actions

### ISSUE THREAD

**Issue by Suzannestacks** [Suzannestacks/Cloudresume#5]

**Comment by Suzannestacks** [comment]
# Task: Setting Github Actions Workflow
- [ ] Create a YAML file that defines the CI/CD pipeline
- [ ] Storing environment variables and secrets to the repository settings.
- [ ] Test the workflow.
- [ ] Verify the actions executed and troubleshoot any issues that arise.
